name: Run Job based on step outputs
on:
  workflow_dispatch:
jobs:
  job_a:
    name: job_a
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job A"
      - id: set
        run: |
          echo "::set-output name=run_job_b::yes"
    outputs:
      run_job_b: ${{ steps.set.outputs.run_job_b }}
  job_b:
    name: job_b
    runs-on: ubuntu-latest
    needs:
      - job_a
    if: needs.job_a.outputs.run_job_b == 'yes'
    steps:
      - run: echo "B"
  c:
    name: c
    runs-on: ubuntu-latest
    needs:
      - job_a
      - job_b
    if: needs.job_b.result == 'success' || needs.job_b.result == 'skipped'
    steps:
      - run: echo "C"
